# Inleiding

Betrouwbare informatie over de toestand en trends van dier- en plantensoorten in Vlaanderen is van
groot belang voor de onderbouwing van het Vlaamse soortenbeleid en voor de 6-jaarlijkse rapportage in kader van de Europese Habitat- en Vogelrichtlijn [@Adriaens2011]. Om aan deze informatiebehoefte te voldoen gingen in de periode 2016-2018 nieuwe meetnetten van start voor de monitoring van 65 Vlaamse en Europees prioritaire soorten. Elk meetnet bestaat uit een aantal vooraf vastgelegde locaties, waar een of meerdere soorten via een gestandaardiseerde methode geteld worden. Het Instituut voor Natuur- en Bosonderzoek (INBO) ontwierp de meetnetten [@DeKnijf2014] op basis van de leidraad voor beleidsgerichte meetnetten [@Wouters2008]. 

Voor het uitvoeren van de meetnettellingen doen we beroep op citizen science. Het zijn dus vrijwilligers die, onder coördinatie van Natuurpunt Studie, de meetnetlocaties bezoeken en de tellingen uitvoeren volgens het opgelegde veldprotocol. Om dit allemaal in goede banen te leiden werd het webportaal [meetnetten.be](https://www.meetnetten.be) ontwikkeld.

Het doel van dit rapport is de voortgang te evalueren van de nieuwe soortenmeetnetten na drie jaar monitoring. We doen dit voor de verschillende onderdelen van de informatiecyclus:

* gegevensinzameling (Hoofdstuk \@ref(h:gegevensinzameling)),
* databeheer (Hoofdstuk \@ref(h:dataontsluiting)),
* gegevensanalyse (Hoofdstuk \@ref(h:gegevensanalyse)),
* rapportage en communicatie (Hoofdstuk \@ref(h:rapportage)).

Voordat we de voortgang van de meetnetten bespreken, herhalen we in Hoofdstuk \@ref(h:doel) eerst nog eens het doel van de meetnetten: welke informatie leveren de meetnetten concreet en voor welke soorten verkrijgen we deze informatie. 

Naast de nieuw opgestarte meetnetten in de periode 2016-2018 zijn er ook meetnetten die al veel langer lopen, voornamelijk voor vogels (Algemene Broedvogelmonitoring Vlaanderen, Bijzondere Broedvogelmonitoring Vlaanderen, Watervogeltellingen) en vissen (Vismeetnet). Deze meetnetten bespreken we niet in dit rapport. Ook de resultaten van de gegevensanalyse bespreken we niet in dit rapport. Daarvoor voorzien we andere kanalen (zie Hoofdstuk \@ref(h:rapportage)).

`r ifelse(doc.type != "html", "Dit rapport bevat enkele interactieve figuren die enkel kunnen bekeken worden op de [website versie](https://inbo.github.io/soortenmeetnetten_progress/) van dit rapport.", "")`

