
# Doel soortenmeetnetten {#h:doel}

## Welke soorten monitoren we via een meetnet {#h:welkesoorten}

Voor twee type soorten streven we naar een monitoring op basis van meetnetten: Europees prioritaire soorten en Vlaamse prioritaire soorten [@Westra2014].

De **Europees prioritaire soorten** (EPS) omvatten: 

* Soorten die op Bijlage II en Bijlage IV van de Habitatrichtlijn (HR) staan.

* Vogels waarvoor er rapportageverplichtingen zijn in kader van de Vogelrichtlijn (VR). Dit zijn alle in het wild broedende vogelsoorten in Vlaanderen en een aantal overwinterende en doortrekkende soorten. 

De **Vlaamse prioritaire soorten** (VPS) omvatten:

* Soorten die niet op een bijlage van de HR of VR staan, maar wel op Europees (Atlantisch)
niveau sterk onder druk staan, en waarvoor Vlaanderen een relevante rol speelt t.a.v. de
Europese populatie.

* Soorten waarvoor een soortenbeschermingsplan (SBP) is opgemaakt of waarvoor er een SBP gepland is in kader van het Soortenbesluit.

Het is echter niet haalbaar om alle EPS en VPS te monitoren via een meetnet. Enerzijds omdat meetnetten heel wat inspanningen vergen, zowel voor de omkadering (meetnetontwerp, kwaliteitszorg) als voor het veldwerk
(opleiding, coördinatie en feedback vrijwilligers). Anderzijds is een meetnet niet altijd praktisch haalbaar, bijvoorbeeld omdat een soort heel moeilijk te detecteren is (zoals bv. de Gladde slang). Daarom maakte INBO en ANB een verdere selectie van soorten waarvoor een meetnet het meest aangewezen is, op basis van beleidsrelevantie en praktische haalbaarheid [@Westra2014]. 

In Bijlage \@ref(h:bijlage) geven we een overzicht van de EPS en VPS en duiden we aan welke soorten we via een meetnet monitoren. Om een meetnet te kunnen ontwerpen is het noodzakelijk dat de verspreiding van de soort goed gekend is. Indien dit niet het geval is plannen we een *inhaalslag* om de verspreiding in kaart te brengen. In Bijlage \@ref(h:bijlage) duiden we aan voor welke soorten dit het geval is. Ook soorten waarvoor een meetnet niet haalbaar of wenselijk is, willen we (met een lagere detailgraad) opvolgen. Hiervoor maken we gebruik van zogenaamde *losse waarnemingen*. Dit zijn waarnemingen die meestal zonder vast protocol werden uitgevoerd op vrij gekozen locaties. Een zeer groot aantal van dergelijke waarnemingen worden ingevoerd in waarnemingen.be. Op basis hiervan kunnen we o.a. een ruwe inschatting maken van trends in de verspreiding van de soorten. In Bijlage \@ref(h:bijlage) geven we eveneens aan welke soorten via losse waarnemingen opgevolgd worden. Naast enkele EPS en VPS, zijn dit ook soorten die op Bijlage V van de HR staan. Ook voor heel wat andere informatienoden, zoals het opmaken van Rode Lijsten, spelen losse waarnemingen een belangrijke rol. 

Er zijn ook enkele nieuwe soorten opgenomen in Bijlage \@ref(h:bijlage) die niet vermeld werden in de blauwdrukken. Deze soorten staan vermeld in de tweede versie van de monitoringsprotocollen. Het gaat om EPS die ten tijde van de opmaak van de blauwdrukken nog niet voorkwamen in Vlaanderen. 

Vogels die tot de EPS/VPS behoren worden niet weergegeven in Bijlage \@ref(h:bijlage). Maar ze worden wel allemaal via een meetnet gemonitord. Het gaat om de al langer lopende meetnetten Algemene en Bijzondere Broedvogelmonitoring Vlaanderen (ABV en BBV), de Watervogeltellingen (WVT) en Slaapplaatstellingen (SPT). Daarnaast is er een meetnet in ontwikkeling: de Schaarse Broedvogelmonitoring Vlaanderen (SBV).

Ten slotte vermelden we dat in [meetnetten.be](https://www.meetnetten.be) naast de doelsoort (de soort in functie waarvan een meetnet werd ontworpen) ook andere soorten kunnen ingevoerd worden die tot de soortgroep van de doelsoort behoren en via hetzelfde veldprotocol geteld kunnen worden. Op die manier bekomen we dus ook gestandaardiseerde tellingen voor andere soorten. We moeten er ons wel van bewust blijven dat de meetnetlocaties werden geselecteerd in functie van de doelsoorten en dat er daarom geen garantie is dat de data voor de overige soorten representatief zijn voor Vlaanderen. 

## Welke informatie halen we uit de meetnetten

De soortenmeetnetten zijn in de eerste plaats ontworpen om *trends in populatiegrootte* op Vlaamse schaal te bepalen. Het gaat daarbij in de eerste plaats om langetermijn trends van 12 en 24 jaar. We streven er naar om met grote zekerheid een daling in populatiegrootte van minstens 24% over 24 jaar te kunnen detecteren. Maar ook voor kortere periodes zullen we trends berekenen. Deze zullen minder precies zijn (want er is minder data beschikbaar), maar op basis daarvan kunnen we wel al sterke wijzigingen in de populatiegrootte detecteren of een indicatie krijgen van de richting waarin de populatiegrootte evolueert. (Verwijzen naar ref gegevensanalyse)

Het is minder evident om de *totale populatiegrootte* te bepalen op basis van de soortenmeetnetten. Voor de meeste soorten is het onmogelijk om alle aanwezige individuen op een meetnetlocatie te tellen. Maar door met een gestandaardiseerd veldprotocol te werken, proberen we wel de detectiekans zo constant mogelijk te houden. M.a.w. we proberen er voor te zorgen dat (binnen een bepaald meetnet) de fractie van de aanwezige individuen dat geteld wordt gelijk is voor verschillende locaties en voor verschillende tijdstippen. Op die manier garanderen we een goede overeenkomst tussen de trends in de getelde aantallen en de trends in de totale populatiegrootte. Als we toch informatie wensen over de totale populatiegrootte, kunnen we deze onrechtstreeks schatten door bijvoorbeeld gebruik te maken van N-mixturemodellen [@royle2014]. Maar op dergelijke schattingen zal er heel wat onzekerheid zitten.

In de soortenmeetnetten wordt de *kwaliteit van het leefgebied* enkel gemonitord voor amfibieën die aan een poel geteld worden (Kamsalamander, Boomkikker, Knoflookpad en Rugstreeppad). Voor andere soorten is het praktisch niet haalbaar om de kwaliteit van het leefgebied te bepalen. Ook *voortplantingssucces* wordt enkel bij de amfibieën opgevolgd. Dit gebeurt door de larven te tellen in de poelen.  

















