---
title: "Voortgangsrapport soortenmeetnetten"
author: 
  - 
    name: "Toon Westra"
    email: "Toon.Westra@inbo.be"
  - 
    name: "Voornaam2 Achternaam2"
    email: "voornaam2.achternaam2@inbo.be"
subtitle: "Een stand van zaken na drie jaar monitoring"
reportnr: "Hier komt de DOI van het rapport"
ordernr: "Het optionele nummer van de opdrachtgever"
link-citations: TRUE
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
    split_by: "chapter+number"
    template: !expr INBOmd::inbo_rapport_css("html")
  bookdown::pdf_book:
    base_format: INBOmd::inbo_rapport
  bookdown::epub_book:
    stylesheet: "css/inbo_rapport.css"
    template: !expr INBOmd::inbo_rapport_css("epub")
---


```{r setup, include = FALSE}
library(knitr)
opts_chunk$set(
  echo = FALSE, 
  eval = TRUE,
  cache = FALSE,
  dpi = 300,
  fig.width = 150 / 25.4,
  fig.height = 100 / 25.4,
  warning = TRUE,
  error = TRUE,
  message = TRUE
)
library(tidyverse)
library(INBOtheme)
theme_set(
  theme_inbo(
    base_family = "Calibri", # "Flanders Art Sans",
    base_size = 12
  )
)
if (!interactive() && opts_knit$get("rmarkdown.pandoc.to") != "html") {
  opts_chunk$set(dev = "cairo_pdf")
  theme_set(
    theme_inbo(
      base_family = "Calibri", # "Flanders Art Sans",
      base_size = 8
    )
  )
}
```


```{r}

library(sf)
```

