
\appendix

#Bijlage: overzicht soorten {#h:bijlage}

```{r, warning=FALSE, message=FALSE}

#gs_ls() 

gs_soorten <- gs_url("https://docs.google.com/spreadsheets/d/1wwOkTnn9U55bBfEU_Jzp-NJCTJJYurRkFEVL3OhUB58", verbose = FALSE)

soorten <- gs_read(gs_soorten, verbose = FALSE)

```

```{r}

soorten %>%
  select("Soortgroep", "Nederlandse naam", "Wetenschappelijke naam",  "Type soort", "Type monitoring", "Status meetnet/ inhaalslag") %>%
  filter(`Type soort` %in% c("EPS", "VPS") & !is.na(`Type soort`)) %>%
  arrange(Soortgroep, `Nederlandse naam`) %>%
  mutate("Wetenschappelijke naam" = str_c("<em>", `Wetenschappelijke naam`, "</em>")) %>%
  datatable(rownames = FALSE,
            filter = 'top',
            escape = FALSE,
            options = list(
              columnDefs = list(list(className = 'dt-center', targets = 3:5)),
              language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Dutch.json'),
              pageLength = 25,
              initComplete = JS(
              "function(settings, json) {",
              "$(this.api().table().header()).css({'font-size': '9px',  'color': 'black'});",
              "}"))) %>%
  formatStyle(columns = colnames(.$x$data), 
              `font-size` = '9px')
  
```

